fix/feedback form
torin-asakura/misik pull request #112
Opened 2023-08-09 19:54 UTC by Amiditin

Задача #108 

Изменения:
- Изменена логика @ui/form модулей: 
  - добавлена типизация
  - изменен нейминг переменных
  - переписан FormContent component
- Добавлена проверка верификации ReCaptcha

2023-08-09 23:20 UTC, TorinAsakura requested changes

2023-08-09 23:20 UTC, TorinAsakura commented on landing/fragments/landing-feedback/package.json
> +    "@types/react": "^17",
ставь точную версию и фиксируй зависимости

2023-08-09 23:20 UTC, TorinAsakura commented on ui/form/src/data/index.ts
> +export * from './verifyRecaptcha.request'
последняя строка, настрой свой ВСкод или я буду тебя постоянно дёргать по этим мелочам

2023-08-09 23:20 UTC, TorinAsakura commented on ui/form/src/data/verifyRecaptcha.request.ts
> +// * API docs https://developers.google.com/recaptcha/docs/verify
Используй формат JDoc пожалуйста

2023-08-09 23:20 UTC, TorinAsakura commented on ui/form/src/form-content/form-content.component.tsx
> +  const [formFieldsValues, setFormFieldsValues] = useState(defaultFormFields);
весь этот файл одна сплошная бага
читай https://github.com/atls/hyperion/wiki/Начало-работы#лучшие-практики

2023-08-10 22:58 UTC, Amiditin commented on landing/fragments/landing-feedback/package.json
> +    "@types/react": "^17",
Хорошо, изначально поставил одну из тех которые были в других воркспейсах

Что конкретно означает?
> фиксируй зависимости

2023-08-10 22:58 UTC, Amiditin commented on ui/form/src/data/index.ts
> +export * from './verifyRecaptcha.request'
Не применял форматирование, my bad

2023-08-12 00:09 UTC, TorinAsakura commented on landing/fragments/landing-feedback/package.json
> +    "@types/react": "^17",
Это значит, что нужно указывать чёткую версию зависимости, без разрешения на апдейт минора (каретка)

2023-08-12 00:11 UTC, TorinAsakura requested changes
у тебя последний коммит с битой подписью

2023-08-14 06:22 UTC, Nelfimov requested changes

2023-08-14 06:22 UTC, Nelfimov commented on ui/form/src/data/useSubmit.ts
> +interface FieldError {
Необходимо вынести интерфейсы в отдельный файл.

2023-08-14 06:22 UTC, Nelfimov commented on ui/form/src/data/useForms.ts
> +export interface FormFieldNode {
Необходимо вынести интерфейсы в отдельный файл.

2023-08-14 06:22 UTC, Nelfimov commented on ui/form/src/data/verifyRecaptcha.request.ts
> +interface ResponseData {
Необходимо вынести интерфейсы в отдельный файл.

2023-08-14 06:22 UTC, Nelfimov commented on ui/form/package.json
>      "@emotion/react": "^11.9.3",
Необходимо избавиться от "^" по всем зависимостям и зафиксировать версии.

2023-08-16 14:21 UTC, Amiditin commented on ui/form/package.json
>      "@emotion/react": "^11.9.3",
@Nelfimov при yarn install возникают предупреждения, пример
```
YN0002: │ @ui/layer@workspace:ui/layer doesn't provide graphql (p45615), requested by @apollo/client
```
Их тоже пофиксить?

2023-08-16 15:53 UTC, Nelfimov commented on ui/form/package.json
>      "@emotion/react": "^11.9.3",
Это предупреждение, что ближайший родитель к apollo не дает graphql. Родитель в данном случае @ui/layout. 

Фиксится легко - в peerDependencies layout добавить graphql. Возможно это спровоцирует аналогичную ошибку у родителя layout. Тогда повторять процесс пока ошибка не уйдет. 

На билд ошибка не влияет, функционал 99% тоже. Если перфекционизма нет - можно пропустить.

2023-08-17 07:19 UTC, Nelfimov approved these changes

2023-08-17 07:19 UTC, Nelfimov commented on forks/react-locomotive-scroll/package.json
> +    "react": "18.0.2",
Обрати внимание, тут ты требуешь фиксированную версию у родителя, а родитель = энтрипоинт дает 17.0.2. Так еще и в `resolutions`  у тебя реакт зафиксирован.

2023-08-17 07:19 UTC, Nelfimov commented on landing/app/package.json
> +    "typescript": "4.3.5"
`typescript` место в `dev`. И надо единую версию что в корне что тут. У нас максимально возможная - 4.6.2.

2023-08-17 07:19 UTC, Nelfimov commented on landing/app/package.json
> +    "next": "12.2.0",
Тут версия `next` отличается от `resolution`

2023-08-17 11:09 UTC, Amiditin commented on forks/react-locomotive-scroll/package.json
> +    "react": "18.0.2",
Поставить `"react": "*"` решение? И кто должен комментарии резолвить: я или автор?

2023-08-17 11:22 UTC, Nelfimov commented on forks/react-locomotive-scroll/package.json
> +    "react": "18.0.2",
Да. 

Резолвит автор пр если устранено без комментариев.

2023-08-17 18:31 UTC, TorinAsakura approved these changes

2023-08-17 18:32 UTC, merged