feat/intersection-observer
torin-asakura/misik pull request #20
Opened 2022-03-18 15:53 UTC by brusselboy

2022-03-22 14:40 UTC, TFK70 requested changes

2022-03-22 14:40 UTC, TFK70 commented on ui/spy-scroll/src/step-display/step-display.component.tsx
> +        О нас
Наименования шагов фетчатся с вордпресса, у них есть локализация, так что это важно

2022-03-22 14:40 UTC, TFK70 commented on ui/spy-scroll/src/step-display/step-display.component.tsx
> +            <TransitionBox height={48} backgroundColor='black' width='100%' />
У тебя transition не будет таким образом работать

2022-03-24 10:46 UTC, TFK70 requested changes
Помимо прочего, при первом рендере страницы у навигейшена кривой цвет:

![image](https://user-images.githubusercontent.com/62806448/159899827-b030e046-4d94-46a8-bf79-63d97c173176.png)

2022-03-24 10:46 UTC, TFK70 commented on landing/index-page/src/index.page.tsx
> +  const { getObserverOptionsServices } = useIntersectionObserverServices((id) => {
Так делать не вариант, это просто тупое дублирование кода

И вообще: если у тебя будет блок our-clients которому тоже понадобится трешхолд 0.3 - ты будешь создавать абсолютно такой же хук useIntersectionObserverOurClients?

2022-03-24 11:48 UTC, brusselboy commented on landing/index-page/src/index.page.tsx
> +  const { getObserverOptionsServices } = useIntersectionObserverServices((id) => {
@TFK70 Пофиксил цвет у навигейшена и избавился от дублирования кода

2022-03-24 11:52 UTC, TFK70 requested changes

2022-03-24 11:52 UTC, TFK70 commented on ui/intersection-observer/src/hooks/use-intersection-observer.hook.ts
> +    const observerServices = new IntersectionObserver(
Помимо дублирование кода проблема была в том, что ты прибивал общее к частному: теперь для того чтобы сделать на блок our-clients трешхолд 0.3 тебе придется создавать для него отдельный IntersectionObserver с тем же содержимым что и тут

2022-03-26 19:42 UTC, TFK70 approved these changes

2022-03-26 19:46 UTC, TorinAsakura approved these changes

2022-03-26 19:46 UTC, merged