fix(common): layout
torin-asakura/misik pull request #81
Opened 2022-07-31 16:55 UTC by brusselboy

2022-08-01 07:48 UTC, TFK70 requested changes
@brusselboy а зачем [здесь](https://github.com/torin-asakura/misik/blob/fix/finalize-layout/ui/drawer/src/drawer-mobile-navigation.component.tsx#L21) height 100%? Из-за него у тебя клик по бэкдропу не регается, и outside click соответственно не работает

2022-08-02 18:32 UTC, TFK70 approved these changes

2022-08-02 20:13 UTC, TFK70 approved these changes

2022-08-03 17:26 UTC, TorinAsakura commented
1. [ ] Шарик неверно спозиционирован по отношению к стелле
2. [ ] Шрифт в Lead текстах должен быть italic
3. [ ] Текстовые блоки должны быть спозиционированны к bottom, без отступов 
![Снимок экрана 2022-08-03 в 20 00 38](https://user-images.githubusercontent.com/3940885/182666647-8d7c5d05-fcf8-4a7a-92e6-9c3a129978fb.png)
4. [ ] Контент в текстовых блоках в блоке услуг явно скомкан, хотя должен быть разбит на верхнюю и нижнюю часть
5. [ ] Внутри линков "подробнее об услуге" находятся button, а не span, которые не соответствуют дизайну
6. [ ] У контентных блоков нет fontSize
7. [ ] У email пропала кнопка копирования
8. [ ] Текст под формой не соответствует дизайну
9. [ ] В английской версии нет времени работы
10. [ ] На странице контактов у футера нет бордер-радиуса
11. [ ] На странице услуги по переезду, буллиты (01,02,03,04) всё ещё не по порядку
12. [ ] На странице услуги по переезду, вёрстка текстовых элементов не соответствует дизайну
13. [ ] На странице услуги по переезду, шарик, также, неверно спозиционирован

2022-08-03 17:32 UTC, TorinAsakura requested changes

2022-08-03 17:32 UTC, TorinAsakura commented on landing/pages/index-page/src/index.page.tsx
> +      <Feedback {...getObserverOptions('feedback', 0.8)} contacts />
отзывы договорились убрать ведь из scrollNav, разве нет? @TFK70

2022-08-03 17:46 UTC, TFK70 commented on landing/pages/index-page/src/index.page.tsx
> +      <Feedback {...getObserverOptions('feedback', 0.8)} contacts />
Это форма обратной связи

2022-08-04 12:57 UTC, brusselboy commented
@TorinAsakura насчёт второго пункта, в фигме просто нельзя нажать именно на выделенный текст, там выбирается весь текст и у него указан italic, на самом деле же италик только у выделенного текста, а не у всего lead текста. Поправь если ошибаюсь

2022-08-04 19:17 UTC, TorinAsakura commented
бэкгаунд неверно спозиционирован

2022-08-04 19:52 UTC, TorinAsakura commented
- [ ] в хиро бэкгаунд неверно спозиционирован
- [ ] в навигации излишняя вложенность, её можно оптимизировать
- [ ] очевидное смещение слоев, см. скрин, полагаю, у тебя там колонка, хотя должна быть строка, из-за этого происходит т.н. "нахлёст"
![Снимок экрана 2022-08-04 в 22 21 47](https://user-images.githubusercontent.com/3940885/182935559-bed72a17-beb0-4ff3-bd1d-c26b21213588.png)
- [ ] текст пользовательского соглашения под кнопкой отправки формы не соответствует дизайну
- [ ] шарик при прокрутке не должен смещаться по оси, он должен просто прокручиваться, без смещений
- [ ] отступ между последним контентным блоком и аккордеонами не соответствует дизайну, 40 лишних пикселей должны быть внутри блока, а не частью общего отступа
- [ ] структура отступов между форматами работы и отзывами реализована через откровенную задницу, придётся структуру перевёрстывать
- [ ] отступ между почтой и социальными сетями не соответствует дизайну
- [ ] отступы в футере
- [ ] на странице переезда, после 4 пунктов, напротив, зачем-то один 160 пиксельный отступ расхреначил по блокам

2022-08-09 12:04 UTC, TFK70 commented
@brusselboy @TorinAsakura насчет "дёргающихся" элементов на сайте

Это общая проблема параллакс скроллов реализованных через transform, в одном locomotive scroll есть как минимум несколько [подобных](https://github.com/locomotivemtl/locomotive-scroll/issues/452) ишью, так что эта проблема чисто системная, на уровне либы

Я пока предлагаю не заострять внимание на этой проблеме

P.S. попробовал другую либу - у нее те же проблемы

2022-08-10 11:56 UTC, TFK70 requested changes
Еще для иконки бургер меню нужно добавить хоть какую-то анимацию. Попробуй сделать через svg morph как я делал в аккордеоне, если не будет получаться - сделай обычный fade-in/fade-out анимацию (плавное появление/исчезновение)

2022-08-10 11:56 UTC, TFK70 commented on landing/fragments/landing-relocation-program-benefits/src/relocation-program-benefits.component.tsx
> +                    marginRight={[0, 0, 68]}
Почему margin, а не Layout с флекс базисом?

2022-08-10 18:58 UTC, TFK70 commented on landing/fragments/landing-relocation-program-benefits/src/relocation-program-benefits.component.tsx
> +                    marginRight={[0, 0, 68]}
@brusselboy понял про какую кашу ты говоришь

Дело в том, что отступ в виде лейаута с флекс базисом - тоже является отдельным элементом, соответственно он будет переносится вместе с остальными на следующую строку, так как у тебя стоит flexWrap

Это решается, если поместить элемент и отступ в один контейнер - тогда не будет такого, что отступ переносится на отдельную строку самостоятельно

2022-08-11 17:54 UTC, TFK70 approved these changes

2022-08-12 16:27 UTC, TorinAsakura approved these changes

2022-08-12 16:28 UTC, merged