Feat/data restructuring
torin-asakura/misik pull request #93
Opened 2022-08-04 17:55 UTC by brusselboy

2022-08-09 13:09 UTC, TFK70 requested changes

2022-08-09 13:09 UTC, TFK70 commented on landing/fragments/landing-about/src/about.component.tsx
> +  let imageUrl = ''
Оно было нужно из-за асинхронности операции, если помнишь мы все данные фетчили прямо в компоненте

Сейчас же у тебя уже есть все необходимые данные в пропсах, в таком реассайне нет необходимости

2022-08-09 13:09 UTC, TFK70 commented on landing/fragments/landing-about/src/about.component.tsx
> +    const leadObject = extractFragment('contentAddons', 'lead', data.about[language])
И от extractFragment и прочих страшных хелперов тоже предполагалось избавиться, но это на твое усмотрение

2022-08-09 13:09 UTC, TFK70 commented on landing/pages/contacts-page/src/queries/feedback.query.ts
> +  if (feedbackData) {
```typescript
if (feedbackData) { return { feedback: { RU: {...}, EN: {...} } } }
else return { feedback: { RU: [], EN: [] } }
```

2022-08-09 13:09 UTC, TFK70 commented on landing/pages/index-page/src/index.page.tsx
> +      <About data={data} {...getObserverOptions('about', 0.6)} />
Я бы на твоем месте сортировал данные прямо тут, в page, а во фрагмент передавал только те данные, которые необходимы фрагменту

Тогда теперь понятно зачем тебе extractFragment

2022-08-09 13:09 UTC, TFK70 commented on landing/pages/index-page/src/index.page.tsx
> +  res.setHeader('Cache-Control', 'public, s-maxage=3600, stale-while-revalidate=300')
Лучше вынести это как util в `@globals/data`

Что-то типа:

```typescript
setCacheHeader({ maxAge: 3600, staleWhileRevalidate: 300 })
```

2022-08-09 16:50 UTC, brusselboy commented on landing/pages/contacts-page/src/queries/feedback.query.ts
> +  if (feedbackData) {
не outdated потому что строка 31 не изменилась

2022-08-09 17:06 UTC, brusselboy commented on landing/fragments/landing-about/src/about.component.tsx
> +  let imageUrl = ''
> Оно было нужно из-за асинхронности операции, если помнишь мы все данные фетчили прямо в компоненте
> 
> Сейчас же у тебя уже есть все необходимые данные в пропсах, в таком реассайне нет необходимости

Данная логика осталась только у hero, если убрать проверку на наличие данных, картинка для бэкграунда не появляется

2022-08-09 17:55 UTC, TFK70 approved these changes

2022-08-10 06:53 UTC, TorinAsakura approved these changes

2022-08-10 06:53 UTC, merged